backends/csharp/Cargo.toml, backends/csharp/src/config.rs, backends/csharp/src/converter.rs, backends/csharp/src/overloads/dotnet.rs, backends/csharp/src/overloads/unity.rs, backends/csharp/src/writer.rs
Thanks for the useful crate.
I'm not good at English, so I'm not sure myself if the code comments included in this PR are appropriate.
=> Add a setting to change the exported symbol names according to the backend naming convention

core/src/core.rs
Added a function to remove items from an inventory which are present in any of a collection of other inventories, and return the result as a new inventory. I'm using this in a project where I want to generate multiple bindings files which expose different levels of access (private functions and public SDK functions). As the private consuming project needs to incorporate both bindings, I need to remove duplicate symbols.
=> Added filter function to inventory

backends/csharp/benches/Interop.common.cs, backends/csharp/benches/Interop.cs, backends/csharp/src/overloads/dotnet.rs, backends/csharp/tests/output_unity/Assets/Interop.common.cs, backends/csharp/tests/output_unity/Assets/Interop.common.cs.expected, backends/csharp/tests/output_unity/Assets/Interop.cs, backends/csharp/tests/output_unity/Assets/Interop.cs.expected, backends/csharp/tests/output_unsafe/Interop.common.cs, backends/csharp/tests/output_unsafe/Interop.common.cs.expected, backends/csharp/tests/output_unsafe/Interop.cs, backends/csharp/tests/output_unsafe/Interop.cs.expected, backends/csharp/tests/output_unsafe/Test.cs
The existing implementation of unsafe copy in C# did not correctly copy the whole length of the array due to omitting the size of the type during the copy operation.
=> Use correct length for C# unsafe copy

core/src/lang/rust.rs
Fixed bug whereby incorrect signatures would be generated for FnPointer types with more than one parameter due to typo in type_info method.
=> Fixed typo bug in FnPointer type_info method

core/src/util.rs
The `sort_types_by_dependencies` function could cause an infinite loop in a case where a type's embedded types contained a type which was not present in the inventory (which can occur as a result of filtering the inventory using the `filter` method). I have modified the function to prevent this by checking if the type was at all present in the original list of types.
=> Modified sort_types_by_dependencies to prevent infinite loop for missing types

backends/csharp/benches/Interop.common.cs, backends/csharp/benches/Interop.cs, backends/csharp/src/overloads/dotnet.rs, backends/csharp/tests/output_unity/Assets/Interop.common.cs, backends/csharp/tests/output_unity/Assets/Interop.common.cs.expected, backends/csharp/tests/output_unity/Assets/Interop.cs, backends/csharp/tests/output_unity/Assets/Interop.cs.expected, backends/csharp/tests/output_unsafe/Interop.common.cs, backends/csharp/tests/output_unsafe/Interop.common.cs.expected, backends/csharp/tests/output_unsafe/Interop.cs, backends/csharp/tests/output_unsafe/Interop.cs.expected
The Span and ReadOnlySpan types are only supported in newer .NET versions (see [here](https://docs.microsoft.com/en-us/dotnet/api/system.readonlyspan-1?view=net-6.0#applies-to)). 
This change puts them behind the [.NET version preprocessor directives](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives) for the versions they support.
=> Only use Span and ReadOnlySpan for supported .NET versions

backends/csharp/tests/output_unsafe/Test.cs
This fixes an issue created by #45 which caused the C# unit tests to fail on older .NET versions,
=> Only run test on supported .NET versions

core/src/lib.rs, proc_macros/src/lib.rs, proc_macros/src/service.rs
This provides an additional _service_ attribute to skip certain methods. Practical if the API is used both in Rust and external languages.
=> Attribute to skip methods in a service

backends/csharp/benches/Interop.cs, backends/csharp/src/overloads/dotnet.rs, backends/csharp/src/overloads/unity.rs, backends/csharp/tests/output_safe/Interop.cs, backends/csharp/tests/output_safe/Interop.cs.expected, backends/csharp/tests/output_unity/Assets/Interop.cs, backends/csharp/tests/output_unity/Assets/Interop.cs.expected, backends/csharp/tests/output_unsafe/Interop.cs, backends/csharp/tests/output_unsafe/Interop.cs.expected
This change adds the documentation from functions to all overloaded functions for the DotNet and Unity writers.
=> Write documentation for DotNet and Unity overloads

backends/cpython/src/docs.rs, backends/cpython/src/writer.rs, backends/csharp/benches/Interop.cs, backends/csharp/src/config.rs, backends/csharp/src/converter.rs, backends/csharp/src/docs.rs, backends/csharp/src/lib.rs, backends/csharp/src/overloads/dotnet.rs, backends/csharp/src/overloads/mod.rs, backends/csharp/src/overloads/unity.rs, backends/csharp/src/writer.rs, backends/csharp/tests/backend_csharp_ui.rs, backends/csharp/tests/output/reference_project.md, backends/csharp/tests/output_safe/Interop.cs, backends/csharp/tests/output_safe/Interop.cs.expected, backends/csharp/tests/output_unity/Assets/Interop.cs, backends/csharp/tests/output_unity/Assets/Interop.cs.expected, backends/csharp/tests/output_unsafe/Interop.cs, backends/csharp/tests/output_unsafe/Interop.cs.expected, core/src/writer.rs
This change adds a C# documentation writer, similar to the one for the CPython backend. Also included is change to a utility function to convert Rust function names to C# function names.
=> Create C# documentation writer

backends/c/src/converter.rs, backends/c/src/writer.rs, backends/c/tests/output_docs_inline/my_header.h, backends/c/tests/output_docs_inline/my_header.h.expected, backends/c/tests/output_nodocs/my_header.h, backends/c/tests/output_nodocs/my_header.h.expected, backends/csharp/benches/Interop.common.cs, backends/csharp/benches/Interop.cs, backends/csharp/src/writer.rs, backends/csharp/tests/output_safe/Interop.common.cs, backends/csharp/tests/output_safe/Interop.common.cs.expected, backends/csharp/tests/output_safe/Interop.cs, backends/csharp/tests/output_safe/Interop.cs.expected, backends/csharp/tests/output_unity/Assets/Interop.common.cs, backends/csharp/tests/output_unity/Assets/Interop.common.cs.expected, backends/csharp/tests/output_unity/Assets/Interop.cs, backends/csharp/tests/output_unity/Assets/Interop.cs.expected, backends/csharp/tests/output_unsafe/Interop.common.cs, backends/csharp/tests/output_unsafe/Interop.common.cs.expected, backends/csharp/tests/output_unsafe/Interop.cs, backends/csharp/tests/output_unsafe/Interop.cs.expected, core/src/patterns/callbacks.rs, reference_project/src/patterns/callbacks.rs, reference_project/src/patterns/slice.rs
I have also added a `call_if_some` function to the callback macro which allows callbacks to be optionally called (without panicing if the fn ptr is null).
=> Use name and parameter names in generated bindings for callback macro

backends/cpython/src/writer.rs, backends/cpython/tests/output/reference_project.py, backends/cpython/tests/output/reference_project.py.expected, backends/cpython/tests/output/tests.py, backends/csharp/src/overloads/dotnet.rs, backends/csharp/src/overloads/unity.rs, core/src/writer.rs, reference_project/src/functions.rs
Previously, if you accessed a slice by a negative index in Python, the slice was accessed out of bounds. This change makes it so that it behaves as the normal Python index accessor. This change also ensures that slices are not accessed by indexed out of bounds.
=> Fix Python negative slice index and check index range

backends/cpython/src/converter.rs, backends/cpython/src/writer.rs, backends/cpython/tests/output/reference_project.md, backends/cpython/tests/output/reference_project.py, backends/cpython/tests/output/reference_project.py.expected, backends/cpython/tests/output/tests.py
This change adds the ability to send in a `ctypes.Array` from Python when the parameter is of type `FFISlice` and automatically create a `FFISlice` before function invocation.
=> Allow ctypes array for slice parameters in Python

backends/cpython/src/converter.rs, backends/cpython/src/writer.rs, backends/csharp/src/converter.rs, backends/csharp/src/docs.rs, backends/csharp/src/writer.rs
Previously, the C# doc writer didn't rename fields based on the `rename_symbols` in the C# config. This change fixes that and creates a utility function to get the correct field name.
=> Respect C# symbol naming in fields for doc writer

backends/cpython/src/converter.rs
Set correct types for return and argument for `ASCIIPointer`
From `str` to `bytes` as it mangles input to send it `str`
=> Python Backend Correct type for `ASCIIPointer`

backends/c/src/writer.rs, backends/cpython/src/writer.rs, backends/csharp/src/writer.rs, core/src/lang/c.rs, core/src/patterns/option.rs, core/src/patterns/slice.rs, proc_macros/Cargo.toml, proc_macros/src/constants.rs, proc_macros/src/functions/freestanding.rs, proc_macros/src/types/enums.rs, proc_macros/src/types/structs.rs, reference_project/src/types.rs
Add support for repr(packed) and repr(align(n)) rust struct in c, c# and python bindings generators.
This update should not affect existing bindings without the packed or align attribute or alter their behavior.
=> Add support for repr(packed) and repr(align(n))

backends/c/src/writer.rs, examples/complex/bindings/c/example_complex.h, examples/complex/tests/bindings.rs
I noticed that the C backend was not writing documentation for struct fields or enum variants. This just adds documentation generation to those as well.
Before, `example_complex.h` generated the following:
```
/// Possible errors in our library.
typedef enum ffierror
{
FFIERROR_OK = 0,
FFIERROR_NULLPOINTERPASSED = 10,
} ffierror;
/// A vector used in our game engine.
typedef struct supercomplexentity
{
vec3 player_1;
vec3 player_2;
uint64_t ammo;
const uint8_t* some_str;
uint32_t str_len;
} supercomplexentity;
```
whereas now it generates
```
/// Possible errors in our library.
typedef enum ffierror
{
/// All went fine.
FFIERROR_OK = 0,
/// Naughty API call detected.
FFIERROR_NULLPOINTERPASSED = 10,
} ffierror;
/// A vector used in our game engine.
typedef struct supercomplexentity
{
vec3 …
```
=> fix: generate documentation of fields and enum variants in the C backend

backends/csharp/tests/output_safe/interop_test.csproj, backends/csharp/tests/output_unsafe/interop_test.csproj, examples/complex/bindings/csharp/interop_test.csproj
netcoreapp was [replaced](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks) with net since v5.
=> use correct framework

core/src/patterns/callbacks.rs
This allows wrappers to be easily (and generically) be implemented for callbacks.
```rust
callback!(MyCallback(value: u32) -> u32);
fn wrap_callback<Arg, Ret, Callback>(wrapper: Callback, arg: Arg) -> Ret
where
Callback: Into<Option<extern "C" fn(Arg) -> Ret>>,
Ret: Default,
{
// log that it was called or something.
if let Some(callback) = wrapper.into() {
callback(arg)
} else {
Default::default()
}
}
#[ffi_function]
#[no_mangle]
pub extern "C" fn pattern_callback_1(callback: MyCallback, x: u32) -> u32 {
wrap_callback(callback, x)
}
```
=> Added support for extracting the fn from a macro callback

core/src/patterns/result.rs, proc_macros/src/service/function_impl.rs
This fixed panic messages being logged as:
`Panic in (...): Any { .. }` (the Any { .. } is literal, it's not a formatted string)
Now they're logged as:
`Panic in (...): <the text of the panic if it's a string>`
This code is based on https://github.com/guswynn/panic-message , which is based on https://github.com/rust-lang/rust/blob/4b9f4b221b92193c7e95b1beb502c6eb32c3b613/library/std/src/panicking.rs#L194-L200
It was verified to work locally with string based panics, custom formats won't work as well, but... dunno what to do about that.
=> Added panic message extraction.

backends/csharp/src/config.rs, backends/csharp/src/lib.rs, backends/csharp/src/overloads/dotnet.rs, backends/csharp/tests/backend_csharp_ui.rs, backends/csharp/tests/output_unsafe/Interop.cs, backends/csharp/tests/output_unsafe/Interop.cs.expected
The hope being this provides support for more exotic memory structures.
This is not behind a version check because it's an explicit option, and it will panic if span is selected but unsafe code support is not.
I'm not sure a good way to require this without a larger API change, and my goal was to make this a small opt-in feature.
Originally I was planning to have it generate overload methods, but if a consumer is using unsafe code and wants to use spans, all signatures will still work with arrays just as well. That code also needed guards to ensure it wouldn't generate duplicates of methods that didn't use spans, which added a lot of complexity.
=> Added support for slice-parameters to be passed in as spans and read-only spans, instead of arrays.

core/src/patterns/slice.rs
This allows FFISlice and FFISliceMut to 'leak' a slice of the backing data, even though the returned slice has a valid actual lifetime.
This allows FFISlice to be a pass-through through type.
=> Remapped the lifetimes of FFISlice and FFISliceMut a bit.

crates/backend_c/src/converter.rs, crates/backend_c/src/lib.rs
Without any public API to construct a new Converter, the 'CWriter' trait cannot be effectively implemented to customize output. This would require *also* implementing the Converter's logic, something which is far more work to do.
If there's some reason this was excluded, please do let me know.
=> Added 'new' Function to C Backend Converter

crates/proc_macros/src/service/function_impl.rs, examples/real_project_layout/core_library_ffi/src/engine.rs
This PR is based on #130, so I could check the tests locally as well. Feel free to not pull those in, or tell me and I'll remove them.
----
This PR fixes #129, as it simply compile-errors when trying to use a first argument that is not either a:
- An actual receiver `(&self, &mut self, self: Box<val>, etc...)`
- A reference to itself `impl Service { fn foo(instance: &Service) { ..} }`
Anything else will fail the equality check and stop compilation.
The error message is not the best, but should give some indication on what went wrong.
Sadly at macro-level there is no way to verify type equality.
There's also IMO quite some unsoundness around lifetimes, but this PR should preserve any previous behaviour (as it only emits a check).
=> Dont allow service fns without self

crates/backend_c/src/converter.rs, crates/backend_c/src/lib.rs, crates/backend_c/src/writer.rs
The CTypeConverter doesn't follow the same pattern as the CWriter (implementing a trait of mostly default fns) making it very difficult to alter the functionality of. In addition, CWriter itself uses a static Converter type, disallowing altering it at all.
This pr changes the Converter CWriter uses to an associated type, allowing any type to be used in implementations of CWriter, whether or not they change any other logic.
I was going to do the same for the Python and C# backends, but I noticed their converters didn't implement Traits at all, so I left them alone. I'm happy to do the same for them if this change is favourable.
This is a breaking change of course since implementations of CWriter will need to add the new associated type (something default assoc types would fix :pensive:).
=> Change CWriter's Converter to an Assoc Type

crates/backend_csharp/src/interop/types/composite.rs, crates/reference_project/src/functions.rs, crates/reference_project/src/types.rs, tests/tests/c_function_styles_typedefs.h, tests/tests/c_reference_project/reference_project.h, tests/tests/cpython_basic.py, tests/tests/cpython_benchmarks/reference_project.py, tests/tests/cpython_reference_project/reference_project.py, tests/tests/csharp_benchmarks/Interop.cs, tests/tests/csharp_overloads_dotnet.cs, tests/tests/csharp_reference_project/Interop.cs, tests/tests/csharp_write_types_all.cs, tests/tests/csharp_write_types_namespace.cs, tests/tests/csharp_write_types_namespace_and_global.cs
I hope this is the last one, same as previous fix just for the string bits that I missed.
=> Fix c# generated string marshalling

crates/backend_csharp/src/interop/types/enums.rs, examples/real_project_layout/core_library_ffi_build/bindings/Interop.cs
There has been a change from `0.14.0` to `0.15.0` that adds support for stateful enums, which is awesome but it make some QOL functions such as `ToString` go away, and forces C# embedders to roll their own implementation for each type. This PR is a suggested naive implementation of a `ToString` generation for enum types for C#.
Please lmk if there are any tests/other changes you'd like me to add, and thank you for all your work!
=> C# Backend: Generate a ToString override for enums

Justfile, tests/src/backend_c.rs, tests/src/backend_csharp.rs, tests/src/lib.rs
Use `just update-bindings`  or run cargo test with INTEROPTOPUS_UPDATE_BINDINGS environment variable set (to any value) to regenerate library bindings.
This replaces the old UPDATE_BINDINGS static boolean and you do not need to change any sources and risk accidentally commiting wrong setting.
=> ✨ Regen mode

.github/workflows/release-plz.yml
This will break if release/master diverge, but we always force push release to the latest release point - only after we start publishing backports this model needs to change.
=> chore(release): Auto sync master to release after publishing a new release
